name: "Infrastructure Deployment"

# Trigger when a pull request is received
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - terraform/**
  pull_request:
    branches:
    - main
    paths:
    - terraform/**
env:
  WORKING_DIRECTORY: "./src/terraform"

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v4
      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Plan
        uses: ./.github/actions/plan.yaml
        with:
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
          BUCKET_REGION: ${{ vars.BUCKET_REGION }}
          BUCKET_KEY: ${{ vars.BUCKET_KEY }}
          
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v4

      - name: Terraform Apply
        uses: ./.github/actions/apply.yaml
        with:
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
          BUCKET_REGION: ${{ vars.BUCKET_REGION }}
          BUCKET_KEY: ${{ vars.BUCKET_KEY }}

